name: custom_refresh_indicator
description: Flutter Widget that make it easy to implement custom refresh indicator.
version: 2.0.0-dev.7
repository: https://github.com/gonuit/flutter-custom-refresh-indicator
issue_tracker: https://github.com/gonuit/flutter-custom-refresh-indicator/issues
homepage: https://github.com/gonuit/flutter-custom-refresh-indicator

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.16.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
