name: custom_refresh_indicator
description: Flutter Widget that make it easy to implement custom refresh indicator.
version: 0.1.01
author: Kamil Klyta <kamilklyta341@gmail.com>
repository: https://github.com/gonuit/flutter-custom-refresh-indicator
issue_tracker: https://github.com/gonuit/flutter-custom-refresh-indicator/issues
homepage: https://github.com/gonuit/flutter-custom-refresh-indicator

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
